package dockerd

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseResolvConf(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "resolv.conf")

	content := `# Generated by NetworkManager
search corp.local
nameserver 10.0.0.53
nameserver 8.8.8.8
options edns0
`
	require.NoError(t, os.WriteFile(path, []byte(content), 0644))

	servers := parseResolvConf(path)
	assert.Equal(t, []string{"10.0.0.53", "8.8.8.8"}, servers)
}

func TestParseResolvConf_MissingFile(t *testing.T) {
	got := parseResolvConf("/nonexistent/resolv.conf")
	assert.Nil(t, got)
}

func TestParseResolvConf_NoNameservers(t *testing.T) {
	tmpDir := t.TempDir()
	path := filepath.Join(tmpDir, "resolv.conf")
	require.NoError(t, os.WriteFile(path, []byte("search example.com\n"), 0644))

	got := parseResolvConf(path)
	assert.Empty(t, got)
}

func TestUnitName(t *testing.T) {
	assert.Equal(t, "dockersnap-env1", unitName("env1"))
	assert.Equal(t, "dockersnap-demo-dev", unitName("demo-dev"))
}

func TestManager_SocketPath(t *testing.T) {
	m := &Manager{runDir: "/run/dockersnap"}
	assert.Equal(t, "/run/dockersnap/env1.sock", m.socketPath("env1"))
}

func TestManager_ReadPid(t *testing.T) {
	tmpDir := t.TempDir()
	pidFile := filepath.Join(tmpDir, "test.pid")
	require.NoError(t, os.WriteFile(pidFile, []byte("12345\n"), 0644))

	m := &Manager{}
	pid, err := m.readPid(pidFile)
	require.NoError(t, err)
	assert.Equal(t, 12345, pid)
}

func TestManager_ReadPid_Missing(t *testing.T) {
	m := &Manager{}
	_, err := m.readPid("/nonexistent.pid")
	require.Error(t, err)
}

func TestManager_ReadPid_Garbage(t *testing.T) {
	tmpDir := t.TempDir()
	pidFile := filepath.Join(tmpDir, "test.pid")
	require.NoError(t, os.WriteFile(pidFile, []byte("not-a-number"), 0644))

	m := &Manager{}
	_, err := m.readPid(pidFile)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "parsing pid")
}
