// Code generated by tygo. DO NOT EDIT.
import type { HealthCheck, PortInfo, ConfigOption } from "./pluginsdk";

//////////
// source: responses.go

/**
 * DaemonHealth is the body of GET /api/v1/health.
 */
export interface DaemonHealth {
  status: string;
  version: string;
  uptime: string;
  started_at: string;
  instances: number /* int */;
  running: number /* int */;
  running_healthy: number /* int */;
  running_unhealthy: number /* int */;
}
/**
 * WorkloadDescribeResponse is the body of GET /api/v1/instances/{name}/workload.
 * Fields are explicit (rather than embedding pluginsdk.DescribeResponse)
 * because tygo doesn't see through anonymous-field embeds — it would
 * emit the embed as `any` in TS. The wire shape is identical to the
 * embed version since Go's JSON marshaler flattens anonymous fields too.
 */
export interface WorkloadDescribeResponse {
  workload_plugin?: string;
  workload_type?: string;
  contract_version?: string;
  status?: string;
  ports?: PortInfo[];
  config?: { [key: string]: any};
  details?: { [key: string]: any};
}
/**
 * WorkloadHealthResponse is the body of GET /api/v1/instances/{name}/workload/health.
 * Three shapes are unified here:
 *   - No-workload instance: WorkloadPlugin="", Healthy=true, Checks=[{
 *     Name:"workload", OK:true, Message:"no workload bound"}].
 *   - Cached entry: WorkloadPlugin set, CheckedAt + ConsecutiveFails
 *     populated, Checks lifted from the cached HealthResponse.
 *   - Fresh poll (?fresh=true): no cache fields, Healthy + Checks
 *     come straight from the plugin.
 * Callers (CLI, dashboard) read the same top-level fields regardless.
 */
export interface WorkloadHealthResponse {
  workload_plugin: string;
  healthy: boolean;
  checks?: HealthCheck[];
  contract_version?: string;
  checked_at?: string;
  consecutive_fails?: number /* int */;
}

//////////
// source: server.go

/**
 * PluginInfo is the public-facing description of a discovered plugin.
 */
export interface PluginInfo {
  name: string;
  status: string;
  error?: string;
  version?: string;
  description?: string;
  supported_contract_versions?: string[];
  config_options?: ConfigOption[];
  schema_digest?: string;
  binary_digest?: string;
}
/**
 * PluginAdmin is the subset of plugin.Manager the API needs.
 */
export type PluginAdmin = any;
/**
 * HealthReader is the subset of instance.HealthCache the API reads.
 */
export type HealthReader = any;
/**
 * Server is the dockersnap REST API server.
 */
export interface Server {
}
