// Code generated by tygo. DO NOT EDIT.

//////////
// source: manager.go

/**
 * ProgressReporter allows emitting progress events during long operations.
 * All methods are safe to call on a nil receiver (no-op).
 */
export interface ProgressReporter {
}
/**
 * ProgressEvent represents a single progress step.
 */
export interface ProgressEvent {
  step: string;
  status: string;
  message?: string;
}
/**
 * RevertOpts configures revert behavior.
 */
export interface RevertOpts {
  Force: boolean;
}
/**
 * DockerdManager defines the interface for Docker daemon operations.
 */
export type DockerdManager = any;
/**
 * PluginRunner is the subset of internal/plugin.Manager that instance.Manager
 * uses. Defined as an interface here so tests don't need to spin up real
 * plugin binaries.
 */
export type PluginRunner = any;
/**
 * Manager orchestrates instance lifecycle operations.
 */
export interface Manager {
}
/**
 * ManagerOpts allows injecting dependencies for testing.
 */
export interface ManagerOpts {
  ZFS: any /* zfs.Commander */;
  Dockerd: DockerdManager;
  State?: any /* state.Store */;
  Proxy?: any /* proxy.Manager */;
  Plugins: PluginRunner;
  Logger?: any /* slog.Logger */;
}
