// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 * PluginInput is the JSON object written to stdin for every command except
 * init and schema.
 */
export interface PluginInput {
  contract_version: string;
  command: string;
  instance_name: string;
  instance: Instance;
  forwarded_ports?: ForwardedPort[];
  env?: { [key: string]: string};
  plugin_config?: { [key: string]: any};
}
/**
 * Instance is the per-instance context surfaced to plugins.
 */
export interface Instance {
  name: string;
  socket: string;
  subnet: string;
  data_root: string;
  host_veth_ip: string;
  ns_veth_ip: string;
  netns_name: string;
  metallb_ip: string;
  created_at: string;
  clone_of?: string;
}
/**
 * ForwardedPort is one entry in the host-side TCP proxy's mapping table.
 * ContainerPort is the actual port the container exposes (e.g. 6443 for
 * kind's API server, 5678 for hashicorp/http-echo). HostPort is the
 * public-facing port the daemon's proxy listens on. Plugins that need to
 * identify which forward corresponds to which of their config values
 * match on ContainerPort.
 */
export interface ForwardedPort {
  label: string;
  container_port: number /* int */;
  host_port: number /* int */;
  protocol: string;
}
/**
 * ConfigType enumerates the value types a plugin can declare for its config options.
 */
export const ConfigTypeString = "string";
export const ConfigTypeInt = "int";
export const ConfigTypeBool = "bool";
export const ConfigTypeStringList = "string-list";
export const ConfigTypePath = "path";
/**
 * Constant names match the type prefix (ConfigType) so tygo's
 * enum_style: "union" mode picks them up and emits a TS string-literal
 * union in dashboard/src/lib/types/pluginsdk.ts. Without the prefix
 * match, the generated TS would fall back to `type ConfigType = string`
 * and lose compile-time exhaustiveness.
 */
export type ConfigType = typeof ConfigTypeString | typeof ConfigTypeInt | typeof ConfigTypeBool | typeof ConfigTypeStringList | typeof ConfigTypePath;
/**
 * ConfigOption is one entry in a plugin's declared config schema.
 */
export interface ConfigOption {
  name: string;
  type: ConfigType;
  default?: any;
  required?: boolean;
  description?: string;
}
/**
 * SchemaResponse is the JSON returned by a plugin's `schema` command.
 */
export interface SchemaResponse {
  contract_version: string;
  supported_contract_versions: string[];
  plugin_name: string;
  plugin_version: string;
  description?: string;
  config_options?: ConfigOption[];
}
/**
 * ValidateResponse is the JSON returned by `validate`. Errors abort the deploy;
 * warnings are logged but don't block.
 */
export interface ValidateResponse {
  contract_version: string;
  valid: boolean;
  errors?: string[];
  warnings?: string[];
}
/**
 * ProgressEvent is one event in an NDJSON progress stream. Matches
 * dockersnap's instance.ProgressEvent so plugin output can be forwarded
 * to API clients verbatim.
 */
export interface ProgressEvent {
  step: string;
  status: string; // "running", "done", "error"
  message?: string;
}
/**
 * AccessResponse is the JSON returned by `access`. Plugins emit token
 * placeholders (${HOST}, ${PORT:label}, ${ACCESS_DIR}) in `Files[].Content`,
 * `Env` values, and (computed) endpoint URLs; core resolves them.
 */
export interface AccessResponse {
  contract_version: string;
  env?: { [key: string]: string};
  files?: File[];
  endpoints?: Endpoint[];
}
/**
 * File is one file the CLI will materialize under the access dir for the user.
 */
export interface File {
  name: string;
  content: string;
  mode: string; // octal string like "0600"
}
/**
 * Endpoint is a structured connection descriptor. The plugin emits the
 * host_port_label; core resolves it to a concrete URL via ForwardedPorts.
 */
export interface Endpoint {
  name: string;
  scheme: string;
  host_port_label?: string;
  insecure?: boolean;
  description?: string;
  url?: string; // populated by core after substitution
}
/**
 * DescribeResponse is the JSON returned by `describe`.
 */
export interface DescribeResponse {
  contract_version: string;
  workload_type: string;
  status: string;
  ports?: PortInfo[];
  config?: { [key: string]: any};
  details?: { [key: string]: any};
}
/**
 * PortInfo is one entry in a workload's advertised ports list.
 */
export interface PortInfo {
  label: string;
  container_port: number /* int */;
  protocol: string;
}
/**
 * HealthResponse is the JSON returned by `health`. Exit code is the source
 * of truth for healthy/unhealthy; the JSON body is for diagnostics.
 */
export interface HealthResponse {
  contract_version: string;
  healthy: boolean;
  checks?: HealthCheck[];
}
/**
 * HealthCheck is one entry in a HealthResponse's check list.
 */
export interface HealthCheck {
  name: string;
  ok: boolean;
  message?: string;
}
/**
 * ErrorResponse is the JSON envelope a plugin may write to stdout when
 * it exits non-zero. If stdout is empty on failure, core uses captured
 * stderr as the error message instead.
 */
export interface ErrorResponse {
  contract_version: string;
  error: string;
  details?: string;
}
