// Code generated by tygo. DO NOT EDIT.

//////////
// source: proxy.go
/*
Package proxy provides a daemon-managed TCP proxy that forwards ports from
the host to instance network namespaces.
*/

/**
 * PortMapping describes a single forwarded port.
 * HostPort is the port the proxy listens on (host-side). DialPort is the
 * port the proxy dials inside the network namespace — typically the same
 * as docker's published host port, which is where docker-proxy listens
 * for the published mapping. InContainerPort is the actual port the
 * container exposes (e.g. 6443 for kind, 5678 for http-echo) and is what
 * plugin authors care about when matching forwarded ports to their config.
 */
export interface PortMapping {
  host_port: number /* int */;
  container_port: number /* int */; // = DialPort; preserved for backwards-compatible JSON
  in_container_port?: number /* int */; // actual in-container port (e.g. 5678 for echo)
  protocol: string;
  description: string;
  /**
   * RequestedHostPort is what the caller (i.e. dockerd via the proxy
   * scan) asked us to listen on. When that port was already taken on
   * the host we fall back to a kernel-picked free port; HostPort then
   * reflects the actual binding while RequestedHostPort preserves the
   * original ask. Equal to HostPort in the common no-collision case;
   * surfaced separately so callers (dashboard, debug tools) can show
   * the discrepancy when present.
   */
  requested_host_port?: number /* int */;
}
/**
 * InstancePorts holds the active port forwarding state for one instance.
 */
export interface InstancePorts {
  instance: string;
  target_ip: string;
  ports: PortMapping[];
}
/**
 * Manager manages TCP port forwarding for all instances.
 */
export interface Manager {
}
