// Code generated by tygo. DO NOT EDIT.

//////////
// source: state.go

/**
 * Status is the lifecycle status of an instance.
 */
export const StatusRunning = "running";
export const StatusStopped = "stopped";
export const StatusError = "error";
export type Status = typeof StatusRunning | typeof StatusStopped | typeof StatusError;
/**
 * SnapshotInfo holds metadata about a snapshot.
 */
export interface SnapshotInfo {
  label: string;
  created_at: string;
  tags?: { [key: string]: string};
}
/**
 * Instance represents the persistent state of a single dockersnap instance.
 */
export interface Instance {
  name: string;
  dataset: string;
  subnet: string;
  subnet_index: number /* int */;
  metallb_ip: string;
  socket: string;
  pid_file: string;
  created_at: string;
  status: Status;
  clone_of?: string;
  snapshots: SnapshotInfo[];
  /**
   * Workload binding. Set on Create; immutable afterward (Revert/Snapshot/
   * Clone never rewrite). Empty WorkloadPlugin means "no workload, plain
   * Docker environment".
   */
  workload_plugin?: string;
  workload_config?: { [key: string]: any};
  workload_contract_version?: string;
}
export type Alias = Instance;
/**
 * State represents the full persistent state of dockersnap.
 */
export interface State {
  instances: { [key: string]: Instance | undefined};
  next_subnet_index: number /* int */;
}
/**
 * Store manages reading and writing the state file.
 * All mutations should go through Update to ensure atomic load-modify-save.
 */
export interface Store {
}
